#define TITLE "TetriC"

#define SCREEN_WIDTH  600
#define SCREEN_HEIGHT 800
#define SCREEN_OFFSET_X (SCREEN_WIDTH - BOARD_WIDTH * CELL_SIZE) / 2
#define SCREEN_OFFSET_Y (SCREEN_HEIGHT - BOARD_HEIGHT * CELL_SIZE) / 2

#define BOARD_WIDTH  10
#define BOARD_HEIGHT 20
#define CELL_SIZE    30


